### ISSUE TITLE
Getting tabular results for story illustrator

### ISSUE THREAD

**Issue by supriya-gdptl** [soumik12345/diffusion-story-illustration#2]
Hi @soumik12345,

Thank you for sharing the blog on story illustrator.
The Results section [link](https://wandb.ai/geekyrakshit/story-illustration/reports/Building-a-GenAI-assisted-automatic-story-illustrator--Vmlldzo5MTYxNTkw?utm_source=course&utm_medium=course&utm_campaign=rag_course#results) shows we need to run `runs.summary["illustrations"]` to get tabular results. Can you tell me where to run this command? I don't see this line being used in either of these Colabs [Story Illustrator.ipynb](https://colab.research.google.com/drive/1R_dw4YaNbcES9p9eCbS40yJ_4EOpkOw_), [illustrate.ipynb](https://colab.research.google.com/github/soumik12345/diffusion-story-illustration/blob/main/examples/illustrate.ipynb).
Appreciate your help.

Thank you,
Supriya

**Comment by soumik12345** [comment]
The tabular results in the report are only for the purpose of presentation. The codebase doesn't log in a tabular manner but in the form of [Weave](https://weave-docs.wandb.ai/) traces, as its mentioned in the readme. When you run the notebook [Story Illustrator.ipynb](https://colab.research.google.com/drive/1R_dw4YaNbcES9p9eCbS40yJ_4EOpkOw_), it should show you a Weave trace link, using which you can explore the detailed trace of the workflow.

**Comment by supriya-gdptl** [comment]
Got it. Thanks.
